# Generated by Django 3.0.8 on 2020-07-04 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='bankName',
            new_name='bank_name',
        ),
    ]
