# Generated by Django 3.0.8 on 2020-07-04 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_auto_20200704_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='accountName',
            new_name='account_name',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='accountNumber',
            new_name='account_number',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='instantWithdrawal',
            new_name='instant_withdrawal',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='interestMax',
            new_name='interest_max',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='interestMin',
            new_name='interest_min',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='predictedInterest',
            new_name='predicted_interest',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='sortCode',
            new_name='sort_code',
        ),
    ]
