# Generated by Django 3.0.8 on 2020-07-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0003_auto_20200704_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='has_interest_max',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='has_interest_min',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='account',
            name='interest_max',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='interest_min',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='sort_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
