# Generated by Django 3.0.8 on 2020-07-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0006_balance_apr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='timestamp',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='balance',
            name='topup',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
