# Generated by Django 3.0.8 on 2020-07-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0007_auto_20200704_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='APR',
            field=models.DecimalField(decimal_places=4, editable=False, max_digits=6, null=True),
        ),
    ]
