# Generated by Django 3.0.8 on 2020-07-04 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0008_auto_20200704_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='has_interest_max',
        ),
        migrations.RemoveField(
            model_name='account',
            name='has_interest_min',
        ),
    ]
