# Generated by Django 3.0.8 on 2020-07-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0009_auto_20200704_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='days_since_last_check',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
